name: "VERDICT iOS Build"

on:
  workflow_dispatch: # Manuel başlatma butonu

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (No Sign)
        run: flutter build ios --release --no-codesign

      - name: Create Payload Folder
        run: |
          mkdir Payload
          cd Payload
          ln -s ../build/ios/iphoneos/Runner.app .
          cd ..
          zip -r VERDICT.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # Sadece burayı v4 yaptım, gerisi aynı.
        with:
          name: VERDICT-IPA
          path: VERDICT.ipa